// A package I developed to house utilities for sending the fake data generated by the
// helper functions in github.com/jamesthecog/fakers.  Note that all requests
// sent by the executable will be buffered by a couple of milliseconds for all
// non-concurrent requests - so that we don't end up stressing the candidate's console
// and / or machine too much.
//
// -- Kevin

package senders

import (
	"context"
	"log"
	"math/rand/v2"
	"runtime"
	"sync"
	"sync/atomic"
	"time"

	// Import the data faker (i.e., our version, no go-faker's) here:
	"github.com/jamesthecog/faker/generator"
)

// No particular reason for setting this to 500 ms - it's just a
// random number I came up with on the fly.  Should work though.
const latency = 500

// Simulate batch requests - heavy requests in other words.
// The `numEntries` parameter will allow candidates to determine
// how light or heavy a payload they want to work with.
func SendBatch(dest string, numEntries int) {
	data := make([]any, numEntries)

	for i := 0; i < len(data); i++ {
		fakeData, err := generator.FakeData()
		if err != nil {
			log.Fatalln(err)
		}
		data[i] = fakeData
	}

	toSend := map[string]any{"data": data}
	SendPayload(dest, toSend)
}

// Simulate high-traffic network with a millisecond cooldown between each
// send to mock network or server latency - all for `duration` seconds:
func HighVolume(dest string, duration int) {
	countDown := time.After(time.Duration(duration) * time.Second)
	numRequests := 0

TimeLoop:
	for {
		select {
		case <-countDown:
			log.Printf("%d seconds is up - %d requests sent!\n", duration, numRequests)
			break TimeLoop
		default:
			payload, err := generator.FakeData()
			if err != nil {
				log.Printf("An error happened while sending data: %v\n", err)
			}
			SendPayload(dest, payload)
			numRequests++
			time.Sleep(time.Millisecond * time.Duration(latency+rand.IntN(latency)))
		}
	}
}

// The function for performing concurrent requests to the endpoint provided - it's not
// functionally different from that HighVolume() function, but it does simulate
// multiple users sending high amounts of data in one go instead of just one
// ultra-motivated person with nothing better to do...
//
// Note that this function will throw cause the program to exit with os.Exit(1) if
// numWorkers is a 1 - there's no point in using this function if the user's machine
// is a potato.
func ConcurrentSending(dest string, numWorkers int, duration int) {
	if numWorkers < 1 {
		log.Fatalf("Your machine only has %d CPUs available - it's too weak to be doing things via concurrency.", runtime.NumCPU())
	}
	var (
		wg            sync.WaitGroup
		responsesSent atomic.Int64
	)
	ctx, cancel := context.WithTimeout(context.Background(), time.Duration(duration)*time.Second)
	defer cancel()

	for i := 0; i < numWorkers; i++ {
		wg.Add(1)
		go worker(ctx, &wg, dest, &responsesSent)
	}

	wg.Wait()
	log.Printf("%d seconds is up - %d requests sent!\n", duration, responsesSent.Load())
}
